--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NoobMCBG/PaidAll
build-by-default: true
branches:
- main
projects:
  PaidAll:
    path: ""
    icon: icon.png
    libs:
      - src: Eric-pm-pl/LibEconomy/LibEconomy
        version: ^1.0.0-alpha
...
