---
name: PaidAll
main: NoobMCBG\PaidAll\PaidAll
api:
- 4.0.0
version: 1.0.0
author: NoobMCBG
description: Paid money to all people online
softdepend: BedrockEconomy, EconomyAPI
permissions:
  paidall.paid:
    description: Permission use commands /paidall
    default: true
...
