---
#   ██████╗░░█████╗░██╗██████╗░░█████╗░██╗░░░░░██╗░░░░░
#   ██╔══██╗██╔══██╗██║██╔══██╗██╔══██╗██║░░░░░██║░░░░░
#   ██████╔╝███████║██║██║░░██║███████║██║░░░░░██║░░░░░
#   ██╔═══╝░██╔══██║██║██║░░██║██╔══██║██║░░░░░██║░░░░░
#   ██║░░░░░██║░░██║██║██████╔╝██║░░██║███████╗███████╗
#   ╚═╝░░░░░╚═╝░░╚═╝╚═╝╚═════╝░╚═╝░░╚═╝╚══════╝╚══════╝

# Message Paid Successfully
# Use {money} to show the amount that player paid
paid-successfully:
  msg: true # false = disable, true = enable;
  msg-paid-successfully: "§a> You have just paid {money} money to all players"

# Broadcast Message Paid
# Use {player} to get the name of the person who paid for the whole server
# Use {money} to show the amount that player paid
broadcast-paid:
  broadcast: true # false = disable, true = enable;
  msg-broadcast-paid: "§a> player {player} just paid everyone {money}$ money !"

# Message Paid Fallied
# Use {price} to show the additional amount to pay
paid-fallied:
  msg: true # false = disable, true = enable;
  msg-paid-fallied: "You need more {price}$ money to paid all players"
...
